# Generated by Django 2.1 on 2019-02-27 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0005_auto_20190227_0734'),
    ]

    operations = [
        migrations.AlterField(
            model_name='friends',
            name='friend_status',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
