# Generated by Django 2.1 on 2019-03-09 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0015_auto_20190309_0716'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_pics',
            field=models.ImageField(blank=True, upload_to='profile_pics'),
        ),
    ]
