# Generated by Django 2.1 on 2019-03-09 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0016_auto_20190309_0741'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_pics',
            field=models.ImageField(blank=True, upload_to='post_pics'),
        ),
    ]
