# Generated by Django 2.1.5 on 2019-03-09 09:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0017_auto_20190309_0815'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='title',
        ),
    ]
