# Generated by Django 3.1.4 on 2021-01-21 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0020_auto_20200916_1511'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-created_date']},
        ),
        migrations.AlterModelOptions(
            name='likes',
            options={'ordering': ['-created_date']},
        ),
    ]
