# Generated by Django 3.1.4 on 2021-01-26 07:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0021_auto_20210121_2014'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={},
        ),
        migrations.AlterModelOptions(
            name='likes',
            options={},
        ),
    ]
